---
title: "Основы обработки данных с помощью R и Dplyr"
subtitle: "Отчет по практике 2"
author: "Zid4a84@yandex.ru"
format: 
  md:
    output-file: README.md
---

## Цель работы

1.  Развить практические навыки использования языка программирования R для обработки данных
2.  Закрепить знания базовых типов данных языка R
3.  Развить практические навыки использования функций обработки данных пакета dplyr – функции select(), filter(), mutate(), arrange(), group_by()

## Исходные данные

1.  Программное обеспечение ОС Windows 11 Pro
2.  RStudio
3.  Интерпретатор языка R 4.5.1

## План

1.  Установть пакет dplyr.

2.  Проанализировать встроенный в пакет dplyr набор данных starwars с помощью языка R и ответить на вопросы:

    1\. Сколько строк в датафрейме?

    2\. Сколько столбцов в датафрейме?

    3\. Как просмотреть примерный вид датафрейма?

    4\. Сколько уникальных рас персонажей (species) представлено в данных?

    5\. Найти самого высокого персонажа.

    6\. Найти всех персонажей ниже 170

    7\. Подсчитать ИМТ (индекс массы тела) для всех персонажей. ИМТ подсчитать по формулe$I=\frac{m}{h^2}$, где 𝑚 – масса (weight), а ℎ – рост (height).

    8\. Найти 10 самых “вытянутых” персонажей. “Вытянутость” оценить по отношению массы (mass) к росту (height) персонажей.

    9\. Найти средний возраст персонажей каждой расы вселенной Звездных войн.

    10\. Найти самый распространенный цвет глаз персонажей вселенной Звездных войн.

    11\. Подсчитать среднюю длину имени в каждой расе вселенной Звездных войн.

## Шаги:

### Установка пакета dplyr, загрузка датасета.

```{r}
options(repos = c(CRAN = "https://mirror.truenetwork.ru/CRAN/"))
install.packages("dplyr")
library(dplyr)
data(starwars)
```

### Анализ датасета и ответы на вопросы

#### Сколько строк в датафрейме?