---
title: "Основы обработки данных с помощью R и Dplyr"
subtitle: "Отчет по практике 3"
author: "Zid4a84@yandex.ru"
format: 
  md:
    output-file: README.md
---

## Цель работы

1.  Развить практические навыки использования языка программирования R для обработки данных
2.  Закрепить знания базовых типов данных языка R
3.  Развить практические навыки использования функций обработки данных пакета dplyr – функции select(), filter(), mutate(), arrange(), group_by()


---

## Исходные данные

1. Программное обеспечение: **OC Windows 11 Pro**  
2. Среда разработки: **RStudio**  
3. Интерпретатор языка: **R 4.5.1**  

---

## План

1.  Установть пакет nycflights13.

2.  Проанализировать встроенный в пакет dplyr набор данных starwars с помощью языка R и ответить на вопросы:

    1.  Сколько встроенных в пакет nycflights13 датафреймов?

    2.  Сколько строк в каждом датафрейме?

    3.  Сколько столбцов в каждом датафрейме?

    4.  Как просмотреть примерный вид датафрейма?

    5.  Сколько компаний-перевозчиков (carrier) учитывают эти наборы данных (представлено в наборах дан- ных)?

    6.  Сколько рейсов принял аэропорт John F Kennedy Intl в мае?

    7.  Какой самый северный аэропорт?

    8.  Какой аэропорт самый высокогорный (находится выше всех над уровнем моря)?

    9.  Какие бортовые номера у самых старых самолетов?

    10. Какая средняя температура воздуха была в сентябре в аэропорту John F Kennedy Intl (в градусах Цельсия).

    11. Самолеты какой авиакомпании совершили больше всего вылетов в июне? Данные i2z1.ddslab.ru 3

    12. Самолеты какой авиакомпании задерживались чаще других в 2013 году?


## Шаги

### Установка пакета nycflights13

```r
install.packages("nycflights13")
install.packages("dplyr")
library(nycflights13)
library(dplyr)
```

### 1. Сколько встроенных в пакет nycflights13 датафреймов?

```r
length(data(package = "nycflights13")$results[, "Item"])
```

### 2. Сколько строк в каждом датафрейме?

```r
data_list <- data(package = "nycflights13")$results[, "Item"]
sapply(data_list, function(x) nrow(get(x)))
```

### 3. Сколько столбцов в каждом датафрейме?

```r
data_list <- data(package = "nycflights13")$results[, "Item"]
sapply(data_list, function(x) ncol(get(x)))
```

### 4. Как просмотреть примерный вид датафрейма?

```r
head(airlines)
```

### 5. Сколько компаний-перевозчиков (carrier) учитывают эти наборы данных (представлено в наборах данных)?

```r
length(unique(airlines$carrier))
```

### 6. Сколько рейсов принял аэропорт John F Kennedy Intl в мае?

```r
nrow(flights[flights$dest == "JFK" & flights$month == 5, ])
```

### 7. Какой самый северный аэропорт?

```r
airports[which.max(airports$lat), ] %>% pull(name)
```

### 8. Какой аэропорт самый высокогорный (находится выше всех над уровнем моря)?

```r
airports[which.max(airports$alt), ] %>% pull(name)
```

### 9. Какие бортовые номера у самых старых самолетов?

```r
planes %>%
filter(!is.na(year)) %>%
arrange(year) %>%
head(10) %>%
select(tailnum, year)
```

### 10. Какая средняя температура воздуха была в сентябре в аэропорту John F Kennedy Intl (в градусах Цельсия).

```r
weather %>%
  filter(origin == "JFK", month == 9) %>%
  summarise(mean_temp_c = (mean(temp, na.rm = TRUE) - 32)* 5/9) %>%
  pull(mean_temp_c)
```

### 11. Самолеты какой авиакомпании совершили больше всего вылетов в июне? Данные i2z1.ddslab.ru 3

```r
flights %>%
  filter(month == 6) %>%
  count(carrier, sort = TRUE) %>%
  slice_max(n, n = 1) %>%
  left_join(airlines, by = "carrier") %>%
  pull(name)
```

### 12. Самолеты какой авиакомпании задерживались чаще других в 2013 году?

```r
flights %>%
  filter(!is.na(dep_delay) & !is.na(arr_delay)) %>%
  mutate(delayed = dep_delay > 0 | arr_delay > 0) %>%
  group_by(carrier) %>%
  summarise(delayed_flights = sum(delayed),
            total_flights = n(),
            delay_ratio = delayed_flights / total_flights) %>%
  arrange(desc(delay_ratio)) %>%
  slice_max(delay_ratio, n = 1) %>%
  left_join(airlines, by = "carrier") %>%
  pull(name)
```

## Оценка результата

В результате лабораторной работы мы развили практические навыки использования языка программирования R для обработки данных и закрепили знания базовых типов данных языка R

## Вывод

Таким образом, мы научились использовать функции обработки данных пакета dplyr – функции select(), filter(), mutate(), arrange(), group_by()